node {
    stage('COMMIT') {
        echo 'The COMMIT stage'
        sh 'mvn -f ~/Project/jenkins-mobile-banking/mobilebanking/pom.xml clean test'
    }
    stage('ACCEPTANCE') {
        echo 'The ACCEPTANCE stage'
        sh 'python ~/Project/jenkins-mobile-banking/robotframework-webdemo/login_tests/test_demoServer.py'
    }
}